### ISSUE TITLE
Transaction Support for migrations.

### ISSUE THREAD

**Issue by Naveen1144** [delium/clickhouse-migrator#4]
Delete and drop happen in the background. Further migrations should happen only after the background migrations has been completed.

**Comment by jpsimonroy** [comment]
Statement pipeline-ing support has been implemented in v1.0.4. 

```migrate('pytest',` 'tests/migrations_seq', 'localhost', 'default', '', queue_exec=False)```
- Argument queue_exec to toggle on and off.
- Argument queue_exec is turned on by default.
- See tests for behaviour
